# ************************************************************************************
#
# Configuration file used for Dev environment
# It can override properties define in application.yml
#
# ************************************************************************************

spring:
  jackson:
    serialization:
      indent-output: true

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    database: MYSQL
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/oauth2
    username: oauth
    password: oauth
    test-on-borrow: true
    validation-query: SELECT 1
    test-while-idle: true
    driver-class-name: com.mysql.jdbc.Driver
#    driver-class-name: oracle.jdbc.OracleDriver
    platform: mysql
    continue-on-error: true


server:
  ssl:
    key-store: classpath:certificates/keystore.p12
    key-store-password: hotelblox
#    key-store-password: api123!
    key-store-type: PKCS12
    key-alias: tomcat

hybris:
  service:
    username: admin
    password: nimda
    baseUrl: http://localhost:9001/purchasingpowerwebservices
    version: v1


oauth:
  baseUrl: https://localhost:8083